# Changes here will be overwritten by Copier
_commit: v1.5.1-198-g14b1baa
_src_path: gh:34j/create-minimal-package
create_minimal_package_installation_ids: '62553233'
github_user: 34j
project_name: vscode-python-extension-core
setup_github: false
setup_npm: false
