# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: 'CHANGELOG.md|.all-contributorsrc'
default_stages: [pre-commit]

ci:
  autofix_commit_msg: 'chore(pre-commit.ci): auto fixes'
  autoupdate_commit_msg: 'chore(pre-commit.ci): pre-commit autoupdate'
  skip: [nixfmt]

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # additional_dependencies won't work for ESM modules
  # https://stackoverflow.com/questions/77253791/how-to-get-new-style-eslint-config-working-with-pre-commit
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.22.0
    hooks:
      - id: eslint
        entry: eslint --fix --no-warn-ignored
        files: ''
        types: [file]
  - repo: https://github.com/NixOS/nixfmt
    rev: '3006577'
    hooks:
      - id: nixfmt
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: pnpm-lock.yaml
