name: Copier Update

on:
  workflow_dispatch:
  schedule:
    - cron: '3 16 * * *'

jobs:
  upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.14'
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - id: copier-update
        run: uvx copier update --trust --vcs-ref main --exclude src --exclude test --exclude package.json --defaults
      - id: copier-recopy
        if: ${{ failure() && steps.copier-update.conclusion == 'failure' }}
        run: uvx copier recopy --trust --vcs-ref main --exclude src --exclude test --exclude package.json --defaults --overwrite
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        if: ${{ steps.copier-update.conclusion == 'success' }}
        with:
          branch: chore/copier-update
          title: 'chore(deps): run `copier update`'
          commit-message: 'chore(deps): run `copier update`'
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        if: ${{ failure() && steps.copier-recopy.conclusion == 'success' }}
        with:
          branch: chore/copier-recopy
          title: 'chore(deps): run `copier recopy`'
          commit-message: 'chore(deps): run `copier recopy`'
