name: Copier Update

on:
  workflow_dispatch:
  schedule:
    - cron: '3 16 * * *'

jobs:
  upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: '3.14'
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - id: copier-update
        run: uvx copier update --trust --vcs-ref main --exclude src --exclude test --exclude package.json --defaults
      - id: copier-recopy
        if: ${{ failure() && steps.copier-update.conclusion == 'failure' }}
        run: uvx copier recopy --trust --vcs-ref main --exclude src --exclude test --exclude package.json --defaults --overwrite
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        if: ${{ steps.copier-update.conclusion == 'success' }}
        with:
          branch: chore/copier-update
          title: 'chore(deps): run `copier update`'
          commit-message: 'chore(deps): run `copier update`'
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        if: ${{ failure() && steps.copier-recopy.conclusion == 'success' }}
        with:
          branch: chore/copier-recopy
          title: 'chore(deps): run `copier recopy`'
          commit-message: 'chore(deps): run `copier recopy`'
